Document: mesos
Title: Debian mesos Manual
Author: <insert document author here>
Abstract: This manual describes what mesos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mesos/mesos.sgml.gz

Format: postscript
Files: /usr/share/doc/mesos/mesos.ps.gz

Format: text
Files: /usr/share/doc/mesos/mesos.text.gz

Format: HTML
Index: /usr/share/doc/mesos/html/index.html
Files: /usr/share/doc/mesos/html/*.html
